move_to_direction:
  description: "Move the camera in the specified direction."
  fields:
    host:
      description: "IP address of the IPC365/360Eye camera. Required."
      example: "192.168.1.68"
      required: true
    camera_type:
      description: "Type of camera to control. Use 'IPC365' for IPC365/360Eye cameras."
      example: "IPC365"
      required: true
    direction:
      description: "Direction to move the camera."
      example: "left"
      required: true
      selector:
        select:
          options:
            - "left"
            - "right"
            - "up"
            - "down"
    move_time:
      description: "Duration of camera movement in seconds."
      example: 0.5
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 10
          step: 0.1
          unit_of_measurement: "s"

move_left:
  description: "Move the camera to the left."
  fields:
    host:
      description: "IP address of the IPC365/360Eye camera. Required."
      example: "192.168.1.68"
      required: true
    camera_type:
      description: "Type of camera to control. Use 'IPC365' for IPC365/360Eye cameras."
      example: "IPC365"
      required: true
    move_time:
      description: "Duration of camera movement in seconds."
      example: 0.5
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 10
          step: 0.1
          unit_of_measurement: "s"

move_right:
  description: "Move the camera to the right."
  fields:
    host:
      description: "IP address of the IPC365/360Eye camera. Required."
      example: "192.168.1.68"
      required: true
    camera_type:
      description: "Type of camera to control. Use 'IPC365' for IPC365/360Eye cameras."
      example: "IPC365"
      required: true
    move_time:
      description: "Duration of camera movement in seconds."
      example: 0.5
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 10
          step: 0.1
          unit_of_measurement: "s"

move_up:
  description: "Move the camera upward."
  fields:
    host:
      description: "IP address of the IPC365/360Eye camera. Required."
      example: "192.168.1.68"
      required: true
    camera_type:
      description: "Type of camera to control. Use 'IPC365' for IPC365/360Eye cameras."
      example: "IPC365"
      required: true
    move_time:
      description: "Duration of camera movement in seconds."
      example: 0.5
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 10
          step: 0.1
          unit_of_measurement: "s"

move_down:
  description: "Move the camera downward."
  fields:
    host:
      description: "IP address of the IPC365/360Eye camera. Required."
      example: "192.168.1.68"
      required: true
    camera_type:
      description: "Type of camera to control. Use 'IPC365' for IPC365/360Eye cameras."
      example: "IPC365"
      required: true
    move_time:
      description: "Duration of camera movement in seconds."
      example: 0.5
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 10
          step: 0.1
          unit_of_measurement: "s"

stop:
  description: "Stop any camera movement immediately."
  fields:
    host:
      description: "IP address of the IPC365/360Eye camera. Required."
      example: "192.168.1.68"
      required: true
    camera_type:
      description: "Type of camera to control. Use 'IPC365' for IPC365/360Eye cameras."
      example: "IPC365"
      required: true
